-- MySQL Script generated by MySQL Workbench
-- Fri Apr 11 08:19:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



-- -----------------------------------------------------
-- Schema Proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Proyecto` ;

-- -----------------------------------------------------
-- Schema Proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto` ;

DROP USER IF EXISTS usuarios2;
CREATE USER "usuarios2"@"%" IDENTIFIED BY "12345";
GRANT SELECT, UPDATE, INSERT, DELETE ON proyecto.* TO usuarios2;

-- -----------------------------------------------------
-- Table `Proyecto`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`usuarios` (
  `idUsuarios` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(120) NOT NULL,
  `tipo_usuario` ENUM('usuario', 'autoridad') NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  `token_Verificacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1020
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`municipios` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`municipios` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idMunicipio`))
ENGINE = InnoDB
AUTO_INCREMENT = 126
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto`.`autoridades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`autoridades` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`autoridades` (
  `idAutoridades` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUsuarios` INT UNSIGNED NOT NULL,
  `Autoridad` VARCHAR(120) NOT NULL,
  `Servicio` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `municipio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idAutoridades`),
  INDEX `fk_Autoridades_Usuarios_idx` (`idUsuarios` ASC) VISIBLE,
  INDEX `fk_municipio` (`municipio` ASC) VISIBLE,
  CONSTRAINT `fk_Autoridades_Usuarios`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `proyecto`.`usuarios` (`idUsuarios`),
  CONSTRAINT `fk_municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `proyecto`.`municipios` (`idMunicipio`))
ENGINE = InnoDB
AUTO_INCREMENT = 1011
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto`.`ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`ubicacion` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`ubicacion` (
  `idUbicacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(80) NOT NULL,
  `Num` VARCHAR(10) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(8) NOT NULL,
  `municipio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUbicacion`),
  INDEX `fk_ubicacion_municipio` (`municipio` ASC) VISIBLE,
  CONSTRAINT `fk_ubicacion_municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `proyecto`.`municipios` (`idMunicipio`))
ENGINE = InnoDB
AUTO_INCREMENT = 1050
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto`.`reportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`reportes` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`reportes` (
  `idReportes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Estado` ENUM('Pendiente', 'Revision', 'Proceso', 'Terminado') NOT NULL,
  `Fecha_Reporte` DATE NOT NULL,
  `Foto` BLOB NULL DEFAULT NULL,
  `idUbicacion` INT UNSIGNED NOT NULL,
  `idUsuarios` INT UNSIGNED NOT NULL,
  `idAutoridades` INT UNSIGNED NOT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idReportes`),
  INDEX `fk_Reportes_Ubicacion1_idx` (`idUbicacion` ASC) VISIBLE,
  INDEX `fk_Reportes_Usuarios1_idx` (`idUsuarios` ASC) VISIBLE,
  INDEX `fk_Reportes_Autoridades1_idx` (`idAutoridades` ASC) VISIBLE,
  CONSTRAINT `fk_Reportes_Autoridades1`
    FOREIGN KEY (`idAutoridades`)
    REFERENCES `proyecto`.`autoridades` (`idAutoridades`),
  CONSTRAINT `fk_Reportes_Ubicacion1`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `proyecto`.`ubicacion` (`idUbicacion`),
  CONSTRAINT `fk_Reportes_Usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `proyecto`.`usuarios` (`idUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb3;

USE `proyecto`;

DELIMITER $$

USE `proyecto`$$
DROP TRIGGER IF EXISTS `proyecto`.`after_delete_reportes` $$
USE `proyecto`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `proyecto`.`after_delete_reportes`
AFTER DELETE ON `proyecto`.`reportes`
FOR EACH ROW
BEGIN
    DELETE FROM ubicacion WHERE idUbicacion = OLD.idUbicacion;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;